### ISSUE TITLE
分布式tensorflow如何关闭server？

### ISSUE THREAD

**Issue by dailong** [Qihoo360/hbox#20]
创建两个ps server，两个worker client，运算然后退出。但是问题是两个worker client运行完退出后，ps server的Container并没有退出，因为还停在server.join()里。

我的问题是：
1. ps server不退出的原因是什么？
2. 如何在client计算完成后关闭server？

**Comment by dailong** [comment]
![image](https://user-images.githubusercontent.com/5086821/37143784-1b51d2bc-22f7-11e8-81ad-594e0f27bc0c.png)
在同一台机器上的两个container不能通信么。一直卡在这不动

**Comment by dailong** [comment]
![image](https://user-images.githubusercontent.com/5086821/37143836-3d6ff482-22f7-11e8-9340-ed9a22aae56c.png)
同一台机器的两个Container不能通信么。worker一直卡着没有日志

**Comment by jiarunying** [comment]
正常情况下，worker运行结束后，am会向ps container发出作业完成信号，ps接收信号自行退出。此处没退出的原因需要排查日志分析。
同台机器可以启两个container，worker卡住需查看逻辑具体分析。是跑的demo出现的问题？

**Comment by dailong** [comment]
是跑Tensorflow demo出现的问题。。现在用了两台机器的NodeManager就是跑不通，其中一个是这个状态一直卡在这，个人感觉是因为另一个worker提前结束了，导致这个worker一直等着通信。
![image](https://user-images.githubusercontent.com/5086821/37204007-99180850-23ca-11e8-8e88-748ae6890762.png)
为什么Container会很快Complete呢？
![image](https://user-images.githubusercontent.com/5086821/37204233-16f0e1b6-23cb-11e8-94e8-68d8bb621736.png)

**Comment by dailong** [comment]
而且demo是没问题的，我把demo.py 在同台机器，和不同机器跑都是没问题的

**Comment by jiarunying** [comment]
麻烦先排查下最早出现COMPLETE状态的container的退出原因（截图中是containerxxx_000003优先退出）：是否存在RUNNING；如果存在RUNNING状态，则查看container日志的最后退出信息；若无，则查看NM端日志判断退出原因。因后边提示有task time out 日志，可能由于container中途被kill等原因导致的异常退出状态，与AM心跳通信超时。

**Comment by dailong** [comment]
@jiarunying 问题找到了。看了下NM日志内存配置小了，这个nodemanager内存怎么从2G突然到了6G

**Comment by dailong** [comment]
@jiarunying 问题找到了。看了下NM日志内存配置小了，这个nodemanager内存怎么从2G突然到了6G
![image](https://user-images.githubusercontent.com/5086821/37325556-6059aec2-26c9-11e8-9f0d-36bfdd890daf.png)

**Comment by dailong** [comment]
@jiarunying Thank you!问题找到了。看了下NM日志内存配置小了，这个NM内存怎么从2G突然到了6G,然后到降下来,没想到这么吃内存
![image](https://user-images.githubusercontent.com/5086821/37325609-8c4cf0ac-26c9-11e8-8d96-168b002d7e42.png)
![image](https://user-images.githubusercontent.com/5086821/37325620-957c530c-26c9-11e8-89a4-6d65d4706a39.png)
