### ISSUE TITLE
任务提交之后创建work和ps container失败 (ln: command not found)

### ISSUE THREAD

**Issue by bleachzk** [Qihoo360/hbox#22]
>Hadoop版本：3.1.0
>XL版本：xlearning-gpu-beta

XL的AM启动之后会通知NodeManager执行launch_container.sh创建work和ps对于的container，执行launch_container.sh会有如下错误：

![1](https://user-images.githubusercontent.com/5548534/37251312-c134dbfe-2548-11e8-8154-d558e033b87e.PNG)
![2](https://user-images.githubusercontent.com/5548534/37251313-c518a5fc-2548-11e8-80fd-eced124cae1d.PNG)
![3](https://user-images.githubusercontent.com/5548534/37251316-c7d1e254-2548-11e8-96bc-478f2786d336.PNG)

ps：如果不是通过XL提交任务，只是提交一个MR任务(wordcount) container创建没有问题。

**Comment by laochangxin** [comment]
Hadoop版本：3.1.0

**Comment by guanghualiu** [comment]
+1 。我也遇到同样的问题
