### ISSUE TITLE
如何获取tensorflow最后保存的模型文件目录

### ISSUE THREAD

**Issue by exitNA** [Qihoo360/hbox#25]
tensorflow的demo跑完后，模型存到了hdfs上其中一个container目录下，除了枚举hdfs上每个目录外，有没有什么方法可以获取模型数据？

**Comment by liyuance** [comment]
获取模型目前只能通过HDFS操作来完成，另外XLearning可以指定参数只允许一个contianer生成模型

**Comment by sinllychen** [comment]
@liyuance 您好，我想问一下，允许生成一个container生成模型，这个container名字能够自己指定吗？
![qq 20180417160407](https://user-images.githubusercontent.com/7518364/38908801-8e74345c-42f4-11e8-9188-8c81c01770b5.png)

**Comment by exitNA** [comment]
@liyuance 可以指定模型在hdfs上的保存路径吗？另外，文档中没找到怎么设定只允许一个container的参数。
