### ISSUE TITLE
Tensorflow任务修改不同worker num，任务提交失败

### ISSUE THREAD

**Issue by sinllychen** [Qihoo360/hbox#32]
对于demo任务，我在submit命令行中，修改了worker的个数>=3的 worker num执行都会失败，不知道什么问题，从DEBUG日志也看不出是什么错。
![qq 20180419111654](https://user-images.githubusercontent.com/7518364/38969498-2e8e8b8a-43c3-11e8-9784-f92d06e31f6c.png)

![qq 20180419111623](https://user-images.githubusercontent.com/7518364/38969480-215aac00-43c3-11e8-993b-a0a1b0f15fd3.png)

**Comment by sinllychen** [comment]
@jiarunying 所以你们在分布式的时候，没有在程序里面对数据进行分片，而是需要提供已经分片好的数据是吗？

**Comment by jiarunying** [comment]
input参数对应输入文件的分发，如果是默认的download的模式，则是以hdfs路径下对应的文件个数为单位进行的分发；如果是STREAM模式，则是按照mr中类似的split大小进行分片分发。

**Comment by sinllychen** [comment]
@jiarunying 我看了一下你们Stream这边的代码，它的分片只分了一片，感觉很奇怪。我觉得这个地方应该是worker的个数才对
![qq 20180419165248](https://user-images.githubusercontent.com/7518364/38981585-53578ffa-43f2-11e8-9107-f37f0e6c5fe5.png)
