### ISSUE TITLE
错误: 找不到或无法加载主类 net.qihoo.xlearning.AM.ApplicationMaster

### ISSUE THREAD

**Issue by whhhy** [Qihoo360/hbox#47]
Application application_1541471478754_0001 failed 2 times due to AM Container for appattempt_1541471478754_0001_000002 exited with exitCode: 1
Failing this attempt.Diagnostics: [2018-11-06 10:32:36.870]Exception from container-launch.
Container id: container_1541471478754_0001_02_000001
Exit code: 1
[2018-11-06 10:32:36.878]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
错误: 找不到或无法加载主类 net.qihoo.xlearning.AM.ApplicationMaster
[2018-11-06 10:32:36.879]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
错误: 找不到或无法加载主类 net.qihoo.xlearning.AM.ApplicationMaster
For more detailed output, check the application tracking page: http://why-System-Product-Name:10086/cluster/app/application_1541471478754_0001 Then click on links to logs of each attempt.
. Failing the application.

各位大佬，跑xlearning-gpu-1.3的run.sh的时候出现这个错误，怎么解决？
环境：
ubuntu16
hadoop3.1.1
xlearning-gpu-1.3

**Comment by lvchigo** [comment]
@whhhy 同样遇到这个问题，请问，问题解决了没？如何解决的？

**Comment by cmonkey** [comment]
方便贴错误日志吗？

**Comment by lvchigo** [comment]
![xlearning-err](https://user-images.githubusercontent.com/8186051/62108495-c63dd100-b2dc-11e9-8169-34e603ddc337.png)
- centos7.6
- hadoop3.1.0
- xlearning-gpu-1.3

**Comment by Su-Wolfe** [comment]
环境：
centos 7.6
hadoop3.1.2
xlearning-gpu-1.3
我也是这个报错，请教解决办法，多谢各位大神!
![TIM截图20190823105617](https://user-images.githubusercontent.com/54424971/63563747-c2783400-c594-11e9-8a5d-e3b84b4454ba.jpg)
![TIM截图20190823105749](https://user-images.githubusercontent.com/54424971/63563781-dcb21200-c594-11e9-818d-5217bb0d1ac6.jpg)

**Comment by ZhuGJ15** [comment]
我也遇到了这个问题，请问有人能解答一下这个该怎么解决吗？

**Comment by jiayuhan-it** [comment]
已支持
