### ISSUE TITLE
INFO Client: reporter progress:100.00%

### ISSUE THREAD

**Issue by Lihengwannafly** [Qihoo360/hbox#48]
![image](https://user-images.githubusercontent.com/24928240/48777374-620a4c80-ed0d-11e8-9049-fd856d939f8a.png)
然后就一直卡在了 INFO Client: reporter progress:100.00%

**Comment by wateryouyou** [comment]
我们也遇到这个问题了，只有启动一个worker时才会运行成功，多个worker时，一直是一个worker success，其它一直卡在reporter progress:100.00%。

请问下这个是什么原因导致的呢？现在有解决办法了吗？

**Comment by jiayuhan-it** [comment]
如有需要请重提issue
