### ISSUE TITLE
无法连接外部数据库

### ISSUE THREAD

**Issue by ghostHBL** [Qihoo360/hbox#49]
自己开发的应用需要连接外部数据库来获取一些信息，但是发现连不上。
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '***' (timed out)")。
不使用XLearning直接利用单机方式是可以连接上这个数据库的。
XLearning不允许在执行期间访问外部链接吗？

**Comment by jiayuhan-it** [comment]
如有需要请重提issue
