### ISSUE TITLE
我运行 examples/tensorflow/run.sh 后一直显示Application report for application_1612431077961_007(state:ACCEPTED)

### ISSUE THREAD

**Issue by my130130** [Qihoo360/hbox#79]
我运行 examples/tensorflow/run.sh 后一直显示
Application report for application_1612431077961_007(state:ACCEPTED)
运行了一天多也还是这样，这是正常还是不正常呢？

**Comment by llwowowowoll** [comment]
我的直接显示  java.io.IOException: Input path /tmp/data/tensorflownot existed!

**Comment by jiayuhan-it** [comment]
如有需要请重提issue
