### ISSUE TITLE
xlearning报错

### ISSUE THREAD

**Issue by lixiang-repo** [Qihoo360/hbox#81]
![image](https://user-images.githubusercontent.com/56247897/126369990-a4db7982-95f2-46cd-91f8-1e8120703c2a.png)

cluster = json.loads(os.environ["TF_CLUSTER_DEF"])
如下：
 {'ps': ['hadoop00:24383'], 'worker': ['hadoop01:22676', 'hdoop02:27181']}

其中一个TF_CONFIG
{"cluster": {"worker": ["hadoop00:22676", "hadoop002:27181    ", "hadoop03:24383"]}, "task": {"type": "worker", "index": 0}}

求解决，折腾一周多了

**Comment by zuston** [comment]
XLearning 似乎不在维护，可以试下 linkedin/TonY @catchlove666

**Comment by jiayuhan-it** [comment]
如有需要请重提issue
